[workspace]
members = [
	"game_sdk",
	"client",
	"perft",
	"player",
	"test_server",
	"dataset",
	"playground"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = true
