[workspace]
members = [
	"game_sdk",
	"xml_client",
	"perft"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = true
[profile.test]
opt-level = 3
